### ISSUE TITLE
Issues while training

### ISSUE THREAD

**Issue by nahidalam** [jmiemirza/MMFM-Challenge#3]
When I start the training with
```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 source scripts/finetune_vicuna13b_clm.sh data_mix ./data/processed_data
```

I get below error

```
  File "/opt/conda/envs/MMFM-Challenge/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './lib/LLaVA/checkpoints/llava-v1.5-13b-pretrain/mm_projector.bin'
```
Indeed there is no `checkpoints` directory inside `lib/LLaVA` 

So I do below

```
~/MMFM-Challenge/lib/LLaVA$ mkdir checkpoints
~/MMFM-Challenge/lib/LLaVA$ cd checkpoints
~/MMFM-Challenge/lib/LLaVA/checkpoints$ git clone https://huggingface.co/liuhaotian/llava-v1.5-13b
~/MMFM-Challenge/lib/LLaVA/checkpoints$ mv llava-v1.5-13b llava-v1.5-13b-pretrain  #rename since the training script is looking for a name like this
```

But I am still getting error
```
FileNotFoundError: [Errno 2] No such file or directory: './lib/LLaVA/checkpoints/llava-v1.5-13b-pretrain/mm_projector.bin'
```

I think this is because in the `scripts/finetune_vicuna13b_clm.sh`, you have `pretrain_mm_mlp_adapter ./lib/LLaVA/checkpoints/llava-v1.5-13b-pretrain/mm_projector.bin` which should be `pretrain_mm_mlp_adapter ./checkpoints/llava-v1.5-13b-pretrain/mm_projector.bin` since you have already done cd to the [lib/LLaVA](https://github.com/jmiemirza/MMFM-Challenge/blob/master/scripts/finetune_vicuna13b_clm.sh#L3) directory.

Once I fix that, I get below error

```
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/envs/MMFM-Challenge/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

So maybe I am not downloading the right checkpoint? Is this the right checkpoint `https://huggingface.co/liuhaotian/llava-v1.5-13b`? Or should I get something else?

**Comment by wlin-at** [comment]
> When I start the training with
> 
> ```
> CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 source scripts/finetune_vicuna13b_clm.sh data_mix ./data/processed_data
> ```
> 
> I get below error
> 
> ```
>   File "/opt/conda/envs/MMFM-Challenge/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
>     super().__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: './lib/LLaVA/checkpoints/llava-v1.5-13b-pretrain/mm_projector.bin'
> ```
> 
> Indeed there is no `checkpoints` directory inside `lib/LLaVA`
> 
> So I do below
> 
> ```
> ~/MMFM-Challenge/lib/LLaVA$ mkdir checkpoints
> ~/MMFM-Challenge/lib/LLaVA$ cd checkpoints
> ~/MMFM-Challenge/lib/LLaVA/checkpoints$ git clone https://huggingface.co/liuhaotian/llava-v1.5-13b
> ~/MMFM-Challenge/lib/LLaVA/checkpoints$ mv llava-v1.5-13b llava-v1.5-13b-pretrain  #rename since the training script is looking for a name like this
> ```
> 
> But I am still getting error
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: './lib/LLaVA/checkpoints/llava-v1.5-13b-pretrain/mm_projector.bin'
> ```
> 
> I think this is because in the `scripts/finetune_vicuna13b_clm.sh`, you have `pretrain_mm_mlp_adapter ./lib/LLaVA/checkpoints/llava-v1.5-13b-pretrain/mm_projector.bin` which should be `pretrain_mm_mlp_adapter ./checkpoints/llava-v1.5-13b-pretrain/mm_projector.bin` since you have already done cd to the [lib/LLaVA](https://github.com/jmiemirza/MMFM-Challenge/blob/master/scripts/finetune_vicuna13b_clm.sh#L3) directory.
> 
> Once I fix that, I get below error
> 
> ```
> return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "/opt/conda/envs/MMFM-Challenge/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
>     magic_number = pickle_module.load(f, **pickle_load_args)
> _pickle.UnpicklingError: invalid load key, 'v'.
> ```
> 
> So maybe I am not downloading the right checkpoint? Is this the right checkpoint `https://huggingface.co/liuhaotian/llava-v1.5-13b`? Or should I get something else?

Hi, 

thanks for the feedback! 
LLaVA training consists of two stages: the first stage of pretraining and the second stage of instruction tuning. To start the second stage, you would need to download the pretrained projector weights of LLaVA 1.5 from the [Huggingface repo](https://huggingface.co/liuhaotian/llava-v1.5-mlp2x-336px-pretrain-vicuna-13b-v1.5) (which contains the `mm_projector.bin`) into the directory of `LLaVA/checkpoints`, and pass `--pretrain_mm_mlp_adapter ./lib/LLaVA/checkpoints/llava-v1.5-mlp2x-336px-pretrain-vicuna-13b-v1.5/mm_projector.bin` in the training script. 
We update the instructions correspondingly! 

Best, 

the MMFM-Challenge team

**Comment by nahidalam** [comment]
Thanks for the quick response @wlin-at 
Just to make sure, the training instructions here (https://github.com/jmiemirza/MMFM-Challenge/blob/master/docs/training.md) are for instruction tuning right? Not for pretraining.

Just want to make sure I get the baseline correct before going into details of performance improvement etc.

**Comment by wlin-at** [comment]
> Thanks for the quick response @wlin-at Just to make sure, the training instructions here (https://github.com/jmiemirza/MMFM-Challenge/blob/master/docs/training.md) are for instruction tuning right? Not for pretraining.
> 
> Just want to make sure I get the baseline correct before going into details of performance improvement etc.

Yes, this is for instruction tuning.

**Comment by nahidalam** [comment]
I followed your update and I am still getting FineNotFound error
```
FileNotFoundError: [Errno 2] No such file or directory: './lib/LLaVA/checkpoints/llava-v1.5-mlp2x-336px-pretrain-vicuna-13b-v1.5/mm_projector.bin'
[2024-03-21 20:03:54,855] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 4638
[2024-03-21 20:03:54,862] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 4639
[2024-03-21 20:03:54,862] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 4640
[2024-03-21 20:03:54,869] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 4641
[2024-03-21 20:03:54,874] [ERROR] [launch.py:321:sigkill_handler] ['/opt/conda/envs/MMFM-Challenge/bin/python3.10', '-u', 'llava/train/train_mem.py', '--local_rank=3', '--deepspeed', './scripts/zero3.json', '--model_name_or_path', 'lmsys/vicuna-13b-v1.5', '--version', 'v1', '--data_path', './data/data_mix.json', '--image_folder', './data/processed_data', '--vision_tower', 'openai/clip-vit-large-patch14-336', '--pretrain_mm_mlp_adapter', './lib/LLaVA/checkpoints/llava-v1.5-mlp2x-336px-pretrain-vicuna-13b-v1.5/mm_projector.bin', '--mm_projector_type', 'mlp2x_gelu', '--mm_vision_select_layer', '-2', '--mm_use_im_start_end', 'False', '--mm_use_im_patch_token', 'False', '--image_aspect_ratio', 'pad', '--group_by_modality_length', 'True', '--bf16', 'True', '--output_dir', './checkpoints/llava-v1.5-13b-clm', '--num_train_epochs', '1', '--per_device_train_batch_size', '16', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '300', '--save_total_limit', '1', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'True', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--report_to', 'wandb'] exits with return code = 1
```
I think you need to change [this line](https://github.com/jmiemirza/MMFM-Challenge/blob/master/scripts/finetune_vicuna13b_clm.sh#L12)

**Comment by nahidalam** [comment]
I changed [this line](https://github.com/jmiemirza/MMFM-Challenge/blob/master/scripts/finetune_vicuna13b_clm.sh#L12) to 

```
--pretrain_mm_mlp_adapter ./checkpoints/llava-v1.5-mlp2x-336px-pretrain-vicuna-13b-v1.5/mm_projector.bin
```

Now the FileNotFound error is gone but I see the error below
```
mm_projector_weights = torch.load(pretrain_mm_mlp_adapter, map_location='cpu')
_pickle  File "/opt/conda/envs/MMFM-Challenge/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
.UnpicklingError: invalid load key, 'v'.
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/envs/MMFM-Challenge/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
Traceback (most recent call last):
  File "/home/ubuntu/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/home/ubuntu/LLaVA/llava/train/train.py", line 875, in train
    model.get_model().initialize_vision_modules(
  File "/home/ubuntu/LLaVA/llava/model/llava_arch.py", line 78, in initialize_vision_modules
    mm_projector_weights = torch.load(pretrain_mm_mlp_adapter, map_location='cpu')
  File "/opt/conda/envs/MMFM-Challenge/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/envs/MMFM-Challenge/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
[2024-03-21 20:12:47,825] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 5400
[2024-03-21 20:12:47,825] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 5401
[2024-03-21 20:12:47,833] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 5402
[2024-03-21 20:12:47,839] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 5403
[2024-03-21 20:12:47,845] [ERROR] [launch.py:321:sigkill_handler] ['/opt/conda/envs/MMFM-Challenge/bin/python3.10', '-u', 'llava/train/train_mem.py', '--local_rank=3', '--deepspeed', './scripts/zero3.json', '--model_name_or_path', 'lmsys/vicuna-13b-v1.5', '--version', 'v1', '--data_path', './data/data_mix.json', '--image_folder', './data/processed_data', '--vision_tower', 'openai/clip-vit-large-patch14-336', '--pretrain_mm_mlp_adapter', './checkpoints/llava-v1.5-mlp2x-336px-pretrain-vicuna-13b-v1.5/mm_projector.bin', '--mm_projector_type', 'mlp2x_gelu', '--mm_vision_select_layer', '-2', '--mm_use_im_start_end', 'False', '--mm_use_im_patch_token', 'False', '--image_aspect_ratio', 'pad', '--group_by_modality_length', 'True', '--bf16', 'True', '--output_dir', './checkpoints/llava-v1.5-13b-clm', '--num_train_epochs', '1', '--per_device_train_batch_size', '16', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '300', '--save_total_limit', '1', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'True', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--report_to', 'wandb'] exits with return code = 1
```
